let myMonsterList = [
    {
        name:"小哈基汪",
        atk:30,
        atkMagic:20,
        def:30,
        defMagic:30,
        life:50,
        nowLife:50,
        speed:60,
        attribute:"土",
        level:1,
        skillList:[
            "摇尾巴","撕咬","低吼","哈基汪大旋风"
        ]
    },
    {
        name:"小哈基汪1",
        atk:30,
        atkMagic:20,
        def:30,
        defMagic:30,
        life:50,
        nowLife:50,
        speed:60,
        attribute:"土",
        level:1,
        skillList:[
            "摇尾巴","撕咬","低吼","哈基汪大旋风"
        ]
    },
    {
        name:"小哈基汪2",
        atk:30,
        atkMagic:20,
        def:30,
        defMagic:30,
        life:50,
        nowLife:50,
        speed:60,
        attribute:"土",
        level:1,
        skillList:[
            "摇尾巴","撕咬","低吼","哈基汪大旋风"
        ]
    },
    {
        name:"小哈基汪3",
        atk:30,
        atkMagic:20,
        def:30,
        defMagic:30,
        life:50,
        nowLife:50,
        speed:60,
        attribute:"土",
        level:1,
        skillList:[
            "摇尾巴","撕咬","低吼","哈基汪大旋风"
        ]
    },
    {
        name:"小哈基汪4",
        atk:30,
        atkMagic:20,
        def:30,
        defMagic:30,
        life:50,
        nowLife:50,
        speed:60,
        attribute:"土",
        level:1,
        skillList:[
            "摇尾巴","撕咬","低吼","哈基汪大旋风"
        ]
    },
    {
        name:"小哈基汪5",
        atk:30,
        atkMagic:20,
        def:30,
        defMagic:30,
        life:50,
        nowLife:50,
        speed:60,
        attribute:"土",
        level:1,
        skillList:[
            "摇尾巴","撕咬","低吼","哈基汪大旋风"
        ]
    }
]
let testBotList = [
    {
        name:"小沙包",
        atk:20,
        atkMagic:20,
        def:20,
        defMagic:20,
        life:80,
        nowLife:80,
        speed:20,
        attribute:"土",
        level:1,
        skillList:[
            "变硬","流沙"
        ]
    }
]
export default {
    getTestMyMonsterList(){
        return myMonsterList
    },
    getTestMyMonsterOn(){
        return {
            ...myMonsterList[0],
            lifeNow:myMonsterList[0].life,
            flash:false,
            helpless:false,
        }
    },
    getTestBotList(){
        return testBotList
    },
    getTestBotOn(){
        return {
            ...testBotList[0],
            lifeNow:testBotList[0].life,
            flash:false,
            helpless:false,
        }
    }
}